version: '3'
services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DATABASE=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_DAYS=300
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_HOST_AUTH_METHOD=trust
      #- POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_DB=postgres
      #- POSTGRES_INITDB_ARGS='-E SQL_ASCII --auth-host=scram-sha-256'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  postgres-db:
