version: '3.3'

services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - '3306:3306'
    # env_file:
    #   - .env

  api:
    build: .
    ports:
      - '80:8000' # server-port:docker-container-port
    environment:
      - DB_USER=root
      - DB_PASSWORD=@root123
      - DB_HOST=mysql
      - DB_PORT=3306
      - DATABASE=admin
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_DAYS=300
    depends_on:
      - mysql
