version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    #image: postgres:latest
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'
    env_file:
      - ./.env

volumes:
  postgres-db:
