name: Build and Deploy Code
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: running git repo
        uses: actions/checkout@v3
      - name: say hi to Pankesh Patel
        run: echo "Pankesh Patel"
