name: Build and Deploy Code

on: [push, pull_request]

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to pankesh
        uses: echo "Pankesh Patel"
