name: Build and Deploy Code
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest # This will tell the job to run on ubuntu machine
    steps:
      - name: running git repo
        uses: actions/checkout@v3 # from marketplace
      - name: say Hi to Pankesh Patel
        run: echo "Pankesh Patel" # This is a command
