name: Build and Deploy Code
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: running git repo
        uses: actions/checkout@v3
      - name: say Hi to Pankesh Patel
        run: echo "Pankesh Patel"
